name = "card-platform-api"
main = "src/index.ts"
compatibility_date = "2023-10-30"

# 环境变量
[env.production.vars]
DATABASE_URL = "your_database_url"
JWT_SECRET = "your_jwt_secret"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"
SITE_URL = "https://yourdomain.com"

# 开发环境
[env.development.vars]
DATABASE_URL = "dev_database_url"
JWT_SECRET = "dev_jwt_secret"